name: Update Profile

on:
  schedule:
    - cron: "0 6 * * *"
  workflow_dispatch:
  push:
    paths:
      - scripts/**

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    concurrency:
      group: profile-stats
      cancel-in-progress: true
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Generate stats
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          USER: alejo54dev
        run: node scripts/generate-stats.js

      - name: Commit & push
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add assets/stats.svg
          git diff --cached --quiet && exit 0
          git commit -m "chore: update stats"
          git push
